# Generated by Django 5.0.1 on 2024-01-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiftyMidcap150',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('shares_traded', models.IntegerField()),
                ('turnover', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NiftyMidcap50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('shares_traded', models.IntegerField()),
                ('turnover', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NiftyNext50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('shares_traded', models.IntegerField()),
                ('turnover', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NiftySmallcap50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('shares_traded', models.IntegerField()),
                ('turnover', models.FloatField()),
            ],
        ),
    ]
